# Generated by Django 4.0.4 on 2022-05-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeeTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, null=True, verbose_name='Date/Time')),
                ('is_reserved', models.BooleanField(default=False, verbose_name='Is Reserved')),
                ('is_using_cart', models.BooleanField(default=False, verbose_name='Using Cart')),
                ('player_count', models.IntegerField(default=0, verbose_name='Player Count')),
                ('holes', models.CharField(choices=[('18', '18'), ('9', '9')], default='18', max_length=2, verbose_name='Holes Playing')),
                ('player_1_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Player 1 Name')),
                ('player_2_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Player 2 Name')),
                ('player_3_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Player 3 Name')),
                ('player_1_is_checkedin', models.BooleanField(default=False, verbose_name='Player 1 Checked In')),
                ('player_2_is_checkedin', models.BooleanField(default=False, verbose_name='Player 2 Checked In')),
                ('player_3_is_checkedin', models.BooleanField(default=False, verbose_name='Player 3 Checked In')),
            ],
            options={
                'verbose_name': 'Tee Times',
                'verbose_name_plural': 'Tee Times',
            },
        ),
    ]
