# Generated by Django 4.0.4 on 2022-05-02 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeeTimes',
        ),
    ]
